# Generated by Django 5.2.16 on 2026-08-06 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_resumebuilder'),
    ]

    operations = [
    ]
